Models/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreViewComponentsExamples.Models
{
    public class City
    {
        public string Name { get; set; }
        public string Country { get; set; }
        public int Population { get; set; }
    }
}

Models/CityViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreViewComponentsExamples.Models
{
    public class CityViewModel
    {
        public int Cities { get; set; }
        public int Population { get; set; }
    }
}

Models/ICityRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreViewComponentsExamples.Models
{
    public interface ICityRepository
    {
        IEnumerable<City> Cites { get; }
        void AddCity(City newCity);
    }
}

Models/IProductRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreViewComponentsExamples.Models
{
    public interface IProductRepository
    {
        IEnumerable<Product> Products { get; }
        void AddProduct(Product newProduct);
    }
}

Models/MemoryCityRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreViewComponentsExamples.Models
{
    public class MemoryCityRepository : ICityRepository
    {
        private List<City> cities = new List<City>
        {
            new City {Name="London", Country="UK", Population=8539000 },
            new City {Name="New York", Country="USA", Population=8406000 },
            new City {Name="San Jose", Country="USA", Population=998537 },
            new City {Name="Paris", Country="France", Population=2244000 }
        };
        public IEnumerable<City> Cites
        {
            get
            {
                return cities;
            }
        }

        public void AddCity(City newCity)
        {
            cities.Add(newCity);
        }
    }
}

Models/MemoryProductRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreViewComponentsExamples.Models
{
    public class MemoryProductRepository : IProductRepository
    {
        private List<Product> products = new List<Product> {
            new Product {Name="Kayak", Price=275M },
            new Product {Name="Lifejacket", Price=48.95M },
            new Product {Name="Soccer ball", Price=19.50M }
        };
        public IEnumerable<Product> Products
        {
            get
            {
                return products;
            }
        }

        public void AddProduct(Product newProduct)
        {
            products.Add(newProduct);
        }
    }
}

Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreViewComponentsExamples.Models
{
    public class Product
    {
        public string Name { get; set; }
        public decimal Price { get; set; }
    }
}

Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreViewComponentsExamples.Models;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace AspNetCoreViewComponentsExamples.Controllers
{
    [ViewComponent(Name = "ComboComponent")]
    public class CityController : Controller
    {
        private ICityRepository repository;

        public CityController(ICityRepository repo)
        {
            repository = repo;
        }
        // GET: /<controller>/
        public ViewResult Create() => View();

        [HttpPost]
        public IActionResult Create(City newCity)
        {
            repository.AddCity(newCity);
            return RedirectToAction("Index", "Home");
        }

        public IViewComponentResult Invoke() => new ViewViewComponentResult() {
            ViewData = new ViewDataDictionary<IEnumerable<City>>(ViewData, repository.Cites)
        };
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreViewComponentsExamples.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace AspNetCoreViewComponentsExamples.Controllers
{
    public class HomeController : Controller
    {
        private IProductRepository repository;

        public HomeController(IProductRepository repo)
        {
            repository = repo;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(repository.Products);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product newProduct)
        {
            repository.AddProduct(newProduct);
            return RedirectToAction("Index");
        }
    }
}

ViewComponents/PocoViewComponent.cs
using AspNetCoreViewComponentsExamples.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreViewComponentsExamples.ViewComponents
{
    public class PocoViewComponent
    {
        private ICityRepository repository;

        public PocoViewComponent(ICityRepository repo)
        {
            repository = repo;
        }

        public string Invoke()
        {
            return $"{repository.Cites.Count()} cities, "
                + $"{repository.Cites.Sum(x => x.Population)} people";
        }
    }
}

Views/City/Create.cshtml
@model City

@{ 
    ViewData["Title"] = "Create City";
    Layout = "_Layout";
}

<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input class="form-control" asp-for="Name" />
    </div>
    <div class="form-group">
        <label asp-for="Country">Country:</label>
        <input class="form-control" asp-for="Country" />
    </div>
    <div class="form-group">
        <label asp-for="Population">Population:</label>
        <input class="form-control" asp-for="Population" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    <a class="btn btn-default" asp-controller="Home" asp-action="Index">Cancel</a>
</form>

Views/Home/Components/CitySummary/CityList.cshtml
@model IEnumerable<City>

<table class="table table-condensed table-bordered">
    @foreach (var city in Model)
    {
        <tr>
            <td>@city.Name</td>
            <td class="text-right">
                @city.Population.ToString()
            </td>
        </tr>

    }
    <tr>
        <th>Total:</th>
        <td class="text-right">
            @Model.Sum(p => p.Population).ToString()
        </td>
    </tr>
</table>

Views/Home/Components/CitySummary/Default.cshtml
@model CityViewModel

<table class="table table-condensed table-bordered">
    <tr>
        <td>Cities:</td>
        <td class="text-right">@Model.Cities</td>
    </tr>
    <tr>
        <td>Population:</td>
        <td class="text-right">
            @Model.Population.ToString("#,###");
        </td>
    </tr>
</table>

Views/Home/Components/PageSize/Default.cshtml
@model long

<div class="panel-body bg-info">
    PageSize: @Model
</div>

Views/Home/Create.cshtml
@model Product

@{ 

    ViewData["Title"] = "Create Product";
    Layout = "_Layout";
}

<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input class="form-control" asp-for="Name" />
    </div>
    <div class="form-group">
        <label asp-for="Price">Price:</label>
        <input class="form-control" asp-for="Price" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    <a class="btn btn-default" asp-action="Index">Cancel</a>
</form>

Views/Home/Index.cshtml
@model IEnumerable<Product>

@{ 
    ViewData["Title"] = "Products";
    Layout = "_Layout";
}

<table class="table table-condensed table-striped table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Price</td>
            </tr>

        }
    </tbody>
</table>
<a asp-action="Create" class="btn btn-primary">Create</a>

Views/Shared/Components/ComboComponent/Default.cshtml
@model IEnumerable<City>

<table class="table table-condensed table-bordered">
    <tr>
        <td>Biggest City:</td>
        <td>
            @Model.OrderByDescending(c => c.Population).First().Name
        </td>
    </tr>
</table>

<a class="btn btn-sm btn-info" asp-controller="City" asp-action="Create">Create City</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body class="panel-body">
    <div class="bg-primary panel-body">
        <div class="row">
                <div class="col-xs-7"><h1>Product</h1></div>
            <div class="col-xs-5">
                @await Component.InvokeAsync("ComboComponent")
                @*<div class="bg-info text-primary panel-body">City Placeholder</div>
                <div class="col-xs-5">@await Component.InvokeAsync("CitySummary", new { showList=true})</div>*@
            </div>
        </div>
       
    </div>
    <div class="panel-body">
        @RenderBody()
    </div>
    @*@await Component.InvokeAsync("PageSize")*@
</body>
</html>